### PR TITLE
Run treefmt in CI

### PR DESCRIPTION
**Pull request by tuxiqae**

### CODE REVIEW

**Comment by tuxiqae** [comment]
@mdarocha It seems to work now, I would honestly move the shell declaration into a shell.nix file and use that, also I would use Cachix in order to shorten the package fetch times

The following commits `1dc3f57eb5bdb3e30d68ab919a7399b162dd384e`, `3033512ea06dc15d14db0a9d6385a09a11790bb8`, and `fed4efd0c94f336bea2fb4e24fd4e1fa1bf47936`  were added in order to verify that the CI indeed passes when no diffs are found, will be dropped later.

**Comment by mrVanDalo** [comment]
So this will create commits, if someone forgets to run treefmt? Or will it reject pushes and pull requests?

**Comment by tuxiqae** [comment]
> So this will create commits, if someone forgets to run treefmt? Or will it reject pushes and pull requests?
The validations in the CI will fail and a merge would not be allowed

**Comment by tuxiqae** [comment]
> Looks good! However, I'd prefer using flakes and `nix run` instead of `nix-shell`, so that the `nixpkgs` version defined in `flake.lock` is used.

For sure, I'm just a Nix noob, so I didn't try doing it by myself

**Comment by mrVanDalo** [comment]
I'll archive this repository now. I created an Issue in the new repository to not forget this pull request. https://github.com/terranix/terranix.github.io/issues/10

**Pull request closed without merging**
